version: '3.8'
services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    depends_on:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./html:/var/www/html
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_NO_ROOT_PASSWORD=1
      - MYSQL_DATABASE=edancy
      - MYSQL_USER=root
      - MYSQL_PASSWORD=dynamos
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
    restart: always
